# --------------------
# Data Settings
# --------------------
data_settings:
  # List of stock tickers to download and process
  tickers: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META', 'JPM', 'PFE', 'XOM', 'PG', 'GE', 'DUK', 'DOW', 'SPG']
  
  # Date range for the entire dataset
  start_date: "2010-01-01"
  end_date: "2024-12-31"

  # Defines the last day of the training data
  train_end_date: '2022-12-31'
  
  # Defines the last day of the validation data
  val_end_date: '2023-12-31'

# --------------------
# Factor Settings
# --------------------
# Defines the factors to be calculated and which agent they belong to.
factor_settings:
  # --- Momentum Agent Factors ---
  # These factors measure the strength, direction, and persistence of trends.
  Momentum:
    RSI_14: { enabled: true, window: 14 }
    MACD:   { enabled: true, fast: 12, slow: 26, signal: 9 }
    EMA_Cross_50_200: { enabled: true, fast: 50, slow: 200 }
    ROC_21: { enabled: true, window: 21 } # Rate of Change over 1 month

  # --- Mean-Reversion Agent Factors ---
  # These factors measure statistical deviation from a recent average.
  MeanReversion:
    BBands_Percent_20: { enabled: true, window: 20, std: 2 }
    RSI_Reversion_14:  { enabled: true, window: 14 } # RSI used to find overbought/oversold

  # --- Shared Factors ---
  # Factors that all agents might find useful for context.
  Shared:
    Volatility_21: { enabled: true, window: 21 }
    Hurst_252:     { enabled: true, window: 252 }

## --------------------
# Model Settings
# --------------------
model_settings:
  # A list of learning rates to test
  learning_rates: [0.0003, 0.0001, 0.000025] 
  total_timesteps: 500000

# --------------------
# Environment Settings
# --------------------
environment_settings:
  initial_balance: 15000
  risk_aversion: 0.3
  lookback_period: 20
  min_data_length: 25


# --------------------
# Reward Function Settings
# --------------------
reward_settings:
  # Penalty for portfolio drawdown
  drawdown_penalty: 0.2
  # Penalty for high portfolio turnover (trading costs)
  turnover_penalty: 0.05
