universe:
  tickers: ["AAPL", "MSFT", "NVDA", "SPY"]
  benchmark: "SPY"

data:
  start_date: "2018-01-01"
  end_date: "2025-08-01"
  price_frequency: "1d"
  source: "yfinance"           # prototype mode; switch to "eodhd" later

eodhd:
  api_key_env: "EODHD_API_KEY"
  rate_limit_per_sec: 4.0

splits:
  train_end: "2023-12-31"
  val_end: "2024-12-31"

factors:
  momentum_21d: {window: 21}
  rsi_14: {window: 14}
  vol_21d: {window: 21}

reward:
  lambda_tc_bps: 1.0           # cost per 100% turnover
  lambda_sigma: 0.10           # volatility penalty
  lambda_dd: 0.05              # drawdown penalty
  turnover_limit_bps: 1000

actions:
  allow_short: false
  max_weight_per_name: 0.10
  cash_node: true

training:
  algo: "PPO"
  total_timesteps: 150000
  n_envs: 4
  seed: 42
  policy_kwargs:
    net_arch:
      pi: [128, 128]
      vf: [128, 128]

eval:
  eval_episodes: 3
  eval_freq_steps: 10000

storage:
  local_data_dir: "data"
  gcs_bucket: ""

logging:
  use_mlflow: false
  mlflow_uri: ""


