data_settings:
  tickers: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META', 'JPM', 'PFE', 'XOM', 'PG', 'GE', 'DUK', 'DOW', 'SPG']
  train_end_date: '2022-12-31'  # Train to 2022
  val_end_date: '2023-12-31'    # New: Val 2023

model_settings:
  learning_rate: 0.0003
  total_timesteps: 500000       # Increased

environment_settings:
  initial_balance: 15000
  risk_aversion: 0.5
  lookback_period: 20
  min_data_length: 250